# ------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED - DO NOT EDIT
# Generated by configure
# To add C++ code, place .cpp files anywhere under src/
# ------------------------------------------------------------------
SOURCES = \
  RcppExports.cpp \
  bgm/bgm_helper.cpp \
  bgm/bgm_logp_and_grad.cpp \
  bgm/bgm_sampler.cpp \
  bgmCompare/bgmCompare_helper.cpp \
  bgmCompare/bgmCompare_logp_and_grad.cpp \
  bgmCompare/bgmCompare_sampler.cpp \
  bgmCompare_interface.cpp \
  bgm_interface.cpp \
  custom_exp.cpp \
  data_simulation.cpp \
  e_exp.cpp \
  mcmc_hmc.cpp \
  mcmc_leapfrog.cpp \
  mcmc_nuts.cpp \
  mcmc_rwm.cpp \
  mcmc_utils.cpp \
  progress_manager.cpp \
  sbm_edge_prior.cpp \

